# Note this is not an exhaustive list of all configuration values
collectors:
  enabled: "cpu,logical_disk,net,os,service,system,terminal_services,license,memory,mssql,time,process,physical_disk" #, physical_disk
#cpu, logical_disk, net, os, service, system, terminal_services, license, memory, mssql, time, process, physical_disk
collector:
  service:
    #exclude: ".+TELEMETRY.+"
    include: ".+SQL.+|.+TELEMETRY.+"
    #include: "MSOLAP.+|SSASTELEMETR.+|MSSQLServerOLAPService"
    #include: ".+ReportServer"
  #mscluster:
  #  enabled: "cluster,network,node,resource,resourcegroup"
  #mssql:
  #  classes-enabled: "accessmethods,availreplica,bufman,databases,dbreplica,genstats,locks,memmgr,sqlstats,sqlerrors,transactions,waitstats"
#  perfdata:
#    # Multidimentinal
#    objects: "MSOLAP:Connection"
#      counters:
#        "Current connections": {}
#        "Current user sessions": {}
#        "Failures/sec": {}
#        "Successes/sec": {}
#        "Requests/sec": {}
#        "Total failures": {}
#        "Total successes": {}
#        "Total requests": {}
#    # Tabluar
#    objects: "MSAS14:Connection"
#      counters:
#        "Current connections": {}
#        "Current user sessions": {}
#        "Failures/sec": {}
#        "Successes/sec": {}
#        "Requests/sec": {}
#        "Total failures": {}
#        "Total successes": {}
#        "Total requests": {}
log:
  level: error #debug, info, warn, error
  format: logfmt
  file: eventlog
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
web:
  listen-address: ":9182"
